### ISSUE TITLE
'gbk' codec can't decode byte 0x82 in position 107: illegal multibyte sequence

### ISSUE THREAD

**Issue by AndyLonly** [jsonzilla/vtt_to_srt3#7]
```
Traceback (most recent call last):
  File "\music_core\ytb_dlr.py", line 203, in file_path
    v2s.vtt_to_srt(file_path + "/" + filename)
  File "\vtt_to_srt\vtt_to_srt.py", line 68, in vtt_to_srt
    file_contents: str = read_text_file(str_name_file)
  File "\vtt_to_srt\vtt_to_srt.py", line 59, in read_text_file
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 107: illegal multibyte sequence
```
The English version is converted normally, but zh-TW does not seem to be converted correctly

[n-BXNXvTvV4.zh-TW.zip](https://github.com/amorvincitomnia/vtt-to-srt.py/files/6352541/n-BXNXvTvV4.zh-TW.zip)

**Comment by jsonzilla** [comment]
Thanks for the file! If have another issue, get in touch.
